import "LoginViewModel.idl";

namespace ContosoAirlinePOSCpp
{
    [default_interface]
    runtimeclass LoginPage : Microsoft.UI.Xaml.Controls.Page
    {
        LoginPage();  
        LoginViewModel  ViewModel{ get; };        
    }
}
