namespace ContosoAirlinePOSCpp
{
    [default_interface]
    runtimeclass SettingsPage : Microsoft.UI.Xaml.Controls.Page
    {
        SettingsPage();
        Int32 SelectedIndex;
        Windows.Foundation.Collections.IObservableVector<String> Themes{ get; };
    }
}
